### ISSUE TITLE
You can parse the data from the actual CBSE website and display the results.

### ISSUE THREAD

**Issue by duttaditya18** [niteshkumarniranjan/CBSE-Result-Site-Redesigned#1]

**Comment by niteshkumarniranjan** [comment]
I made this website when I have no Knowledge of JavaScript.
So I have no dynamism on the website but I will make.
thank you! for suggesting. @duttaditya18 
Or if you want to contribute then you could implement this because this is your Idea!

**Comment by duttaditya18** [comment]
@niteshkumarniranjan Okay cool! I will try doing this.
